services:
  # Service de base de données PostgreSQL
  echo-db:
    image: postgres:17-alpine
    container_name: echo-db
    ports:
      - "${DB_PORT:-5432}:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Service Backend Node.js / Express
  echo-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: echo-server
    command: pnpm run dev
    ports:
      - "${PORT:-4000}:${PORT:-4000}"
    volumes:
      - .:/app
      - pnpm_modules:/app/node_modules # Volume nommé pour isoler et persister les node_modules de Docker
    environment:
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - CI=true
    depends_on:
      - echo-db

# Déclaration des volumes persistants
volumes:
  postgres_data:
  pnpm_modules:
